name: build and push docker image

on: 
  branches: 
    - main

jobs: 
  buildImage: 
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Setting up docker buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with: 
        install: true
    - name: Build image
      run: docker build . 

    #add step to push image to artifact repository