name: build and push docker image

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs: 
  buildImage: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #authenticate against gh container registry
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GHCR_PAT}}

      - name: Setting up docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/tbm5k/bonfire-frontend:latest
