name: build and push docker image

on: 
  push:
    branches: 
      - main
  workflow_dispatch:

jobs: 
  buildImage: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #authenticate against gh container registry
      # - name: Login to ghcr
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{github.actor}}
      #     password: ${{secrets.GHCR_PAT}}

      # set up gcloud cli
      - name: setting up gloud cli
        uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - run: |-
          gcloud --quiet auth configure-docker
      - name: Setting up docker buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          # tags: ghcr.io/tbm5k/bonfire-frontend:latest
          tags: gcr.io/${{secrets.GCP_PROJECT_ID}}/bonfire-frontend:latest
