name: bonfire ci

on: 
  push:
    branches:
      - main

jobs: 
  run_test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.15.4'
      - run: npm ci
      - run: npm test
